/**
 * locParser.ts
 *
 * Utilities for:
 *  1. Detecting AI-generated commits via configurable pattern matching.
 *  2. Normalising raw LOC counts (optional whitespace discount).
 *  3. Aggregating a flat list of raw GitLab commits into per-developer stats.
 *
 * AI Detection Strategy
 * ─────────────────────
 * We scan the full commit message (title + body) against a list of regex
 * patterns that correspond to known AI tool conventions:
 *
 *  [AI], [AI-Generated], [AI-Assisted]
 *    → Manual tagging convention — developers explicitly mark AI code.
 *
 *  co-pilot:, copilot:, [Copilot], github-copilot
 *    → GitHub Copilot commit conventions.
 *
 *  [Claude], claude:, claude-ai
 *    → Anthropic Claude commit conventions.
 *
 *  [ChatGPT], chatgpt:, [Cursor], cursor-ai, [Gemini], gemini:
 *    → Other popular AI coding tools.
 *
 *  Co-Authored-By: *[bot]*
 *    → GitHub/GitLab bot trailer — common when AI tools commit autonomously.
 *
 * All patterns are case-insensitive.
 *
 * LOC Calculation
 * ───────────────
 * We count `additions` from the GitLab commit stats as the primary LOC
 * metric because it represents new code written, while `deletions`
 * represent removed code. Merge commits are excluded upstream to avoid
 * double-counting lines already present in the feature branch commits.
 *
 * The optional whitespace discount applies a conservative 5% reduction to
 * account for blank lines and formatting-only changes that inflate raw counts.
 */

import type {
  RawGitLabCommit,
  EnrichedCommit,
  DeveloperStats,
  GlobalSummary,
} from '../types';

// ─── AI Pattern Registry ──────────────────────────────────────────────────────

/**
 * Each entry is a RegExp tested against the full commit message text.
 * Add or remove patterns here to tune detection for your team's conventions.
 */
export const AI_PATTERNS: RegExp[] = [
  // Generic manual tagging
  /\[AI\]/i,
  /\[AI[- ]Generated\]/i,
  /\[AI[- ]Assisted\]/i,
  /\bai[- ]generated\b/i,
  /\bgenerated by ai\b/i,

  // GitHub Copilot
  /\bco-pilot:/i,
  /\bcopilot:/i,
  /\[copilot\]/i,
  /\bgithub[- ]copilot\b/i,

  // Anthropic Claude
  /\[claude\]/i,
  /\bclaude:/i,
  /\bclaude[- ]ai\b/i,

  // OpenAI ChatGPT
  /\[chatgpt\]/i,
  /\bchatgpt:/i,

  // Cursor AI
  /\[cursor\]/i,
  /\bcursor[- ]ai\b/i,

  // Google Gemini
  /\[gemini\]/i,
  /\bgemini:/i,

  // Bot co-author trailer (used by autonomous AI agents)
  /Co-Authored-By:.*\[bot\]/i,
  /Co-Authored-By:.*bot@/i,
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns the median of a numeric array, or 0 for an empty array. */
function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (sorted[mid - 1] + sorted[mid]) / 2
    : sorted[mid];
}

// ─── Detection ────────────────────────────────────────────────────────────────

/**
 * Returns 'pattern' if any AI pattern matches in the commit title or body,
 * otherwise null.
 *
 * @param title   - The first line / subject of the commit message
 * @param message - Full commit message body
 */
export function isAiGeneratedCommit(
  title: string,
  message: string
): 'pattern' | null {
  const fullText = `${title}\n${message}`;
  return AI_PATTERNS.some((pattern) => pattern.test(fullText))
    ? 'pattern'
    : null;
}

/**
 * Multiplier above a developer's median additions that triggers the
 * LOC-burst heuristic. A commit must be at least this many times larger
 * than the developer's own median to be flagged.
 */
const LOC_BURST_MULTIPLIER = 3;

// ─── LOC Normalisation ────────────────────────────────────────────────────────

/**
 * Calculates effective LOC from raw addition counts.
 *
 * @param additions              - Raw addition count from GitLab stats
 * @param applyWhitespaceDiscount - When true, apply a 5% reduction to
 *                                  approximate whitespace-only lines.
 *                                  Exact filtering requires fetching full
 *                                  diffs which is prohibitively expensive.
 */
export function calculateEffectiveLOC(
  additions: number,
  applyWhitespaceDiscount: boolean
): number {
  if (applyWhitespaceDiscount) {
    return Math.round(additions * 0.95);
  }
  return additions;
}

// ─── Aggregation ──────────────────────────────────────────────────────────────

/**
 * Groups a flat list of raw GitLab commits by author email and computes
 * per-developer statistics.
 *
 * Algorithm:
 *  1. Iterate over every commit.
 *  2. Key the developer map by lowercased author_email (stable across renames).
 *  3. Classify the commit as AI or Manual.
 *  4. Accumulate LOC, commit counts, and the enriched commit object.
 *  5. Return sorted by totalLOC descending.
 *
 * @param rawCommits              - Commits from GitLab, each optionally tagged
 *                                  with _projectId (injected by the service layer)
 * @param applyWhitespaceDiscount - Passed through to calculateEffectiveLOC
 */
export function aggregateByDeveloper(
  rawCommits: (RawGitLabCommit & { _projectId?: string })[],
  applyWhitespaceDiscount: boolean
): DeveloperStats[] {
  // ── Pass 1: group commits by author and apply pattern + committer signals ──
  const statsMap = new Map<string, DeveloperStats>();
  // Track raw additions per developer for the LOC-burst pass
  const additionsByDev = new Map<string, number[]>();

  for (const commit of rawCommits) {
    const key = commit.author_email.toLowerCase();

    if (!statsMap.has(key)) {
      statsMap.set(key, {
        authorName: commit.author_name,
        authorEmail: commit.author_email,
        totalCommits: 0,
        manualCommits: 0,
        aiCommits: 0,
        totalAdditions: 0,
        totalDeletions: 0,
        totalLOC: 0,
        manualLOC: 0,
        aiLOC: 0,
        commits: [],
      });
      additionsByDev.set(key, []);
    }

    const additions = commit.stats?.additions ?? 0;
    additionsByDev.get(key)!.push(additions);

    const deletions = commit.stats?.deletions ?? 0;
    const effectiveLOC = calculateEffectiveLOC(additions, applyWhitespaceDiscount);
    const isMerge = commit.parent_ids.length > 1;

    // Signal 1 — commit message patterns
    let aiReason: EnrichedCommit['aiReason'] = isAiGeneratedCommit(
      commit.title,
      commit.message ?? ''
    );

    // Signal 2 — committer email differs from author email (tool committed on
    // behalf of the developer, e.g. Copilot, Cursor, or a bot agent)
    if (
      !aiReason &&
      commit.committer_email &&
      commit.committer_email.toLowerCase() !== commit.author_email.toLowerCase()
    ) {
      aiReason = 'committer-mismatch';
    }

    const enriched: EnrichedCommit = {
      id: commit.id,
      shortId: commit.short_id,
      title: commit.title,
      message: commit.message ?? '',
      authorName: commit.author_name,
      authorEmail: commit.author_email,
      authoredDate: commit.authored_date,
      projectId: commit._projectId ?? 'unknown',
      additions,
      deletions,
      total: commit.stats?.total ?? 0,
      isAiGenerated: aiReason !== null,
      aiReason,
      isMergeCommit: isMerge,
    };

    const devStats = statsMap.get(key)!;
    devStats.commits.push(enriched);
    devStats.totalCommits += 1;
    devStats.totalAdditions += additions;
    devStats.totalDeletions += deletions;
    devStats.totalLOC += effectiveLOC;

    if (aiReason !== null) {
      devStats.aiCommits += 1;
      devStats.aiLOC += effectiveLOC;
    } else {
      devStats.manualCommits += 1;
      devStats.manualLOC += effectiveLOC;
    }
  }

  // ── Pass 2: LOC-burst detection ────────────────────────────────────────────
  // Now that we have all additions for each developer, compute their median
  // and back-flag any manual commit that is suspiciously large.
  for (const [key, devStats] of statsMap) {
    const devMedian = median(additionsByDev.get(key) ?? []);
    // Only apply when the developer has a meaningful baseline (>= 5 commits)
    if (devStats.totalCommits < 5 || devMedian === 0) continue;

    for (const commit of devStats.commits) {
      if (commit.aiReason !== null) continue; // already classified
      if (commit.additions < devMedian * LOC_BURST_MULTIPLIER) continue;

      // Re-classify as AI and update the running totals
      const effectiveLOC = calculateEffectiveLOC(
        commit.additions,
        applyWhitespaceDiscount
      );
      commit.isAiGenerated = true;
      commit.aiReason = 'loc-burst';

      devStats.manualCommits -= 1;
      devStats.manualLOC -= effectiveLOC;
      devStats.aiCommits += 1;
      devStats.aiLOC += effectiveLOC;
    }
  }

  return Array.from(statsMap.values()).sort((a, b) => b.totalLOC - a.totalLOC);
}

/**
 * Collapses per-developer stats into a single global summary for the KPI cards.
 */
export function computeGlobalSummary(developers: DeveloperStats[]): GlobalSummary {
  const totals = developers.reduce(
    (acc, dev) => ({
      totalCommits: acc.totalCommits + dev.totalCommits,
      totalLOC: acc.totalLOC + dev.totalLOC,
      manualLOC: acc.manualLOC + dev.manualLOC,
      aiLOC: acc.aiLOC + dev.aiLOC,
    }),
    { totalCommits: 0, totalLOC: 0, manualLOC: 0, aiLOC: 0 }
  );

  return {
    ...totals,
    totalDevelopers: developers.length,
    aiPercentage:
      totals.totalLOC > 0
        ? Math.round((totals.aiLOC / totals.totalLOC) * 100)
        : 0,
  };
}
